//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.261
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Dir.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The_Dir.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap dir {
            get {
                object obj = ResourceManager.GetObject("dir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dir_008 {
            get {
                object obj = ResourceManager.GetObject("dir_008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *.3
        ///*.A
        ///*.A01
        ///*.A02
        ///*.A03
        ///*.A04
        ///*.A05
        ///*.A06
        ///*.A07
        ///*.A08
        ///*.A09
        ///*.A10
        ///*.A11
        ///*.A2A
        ///*.A2FC
        ///*.A2HR
        ///*.A2LC
        ///*.A2M
        ///*.A3
        ///*.A31
        ///*.A3K
        ///*.A3L
        ///*.A3M
        ///*.A3W
        ///*.A41
        ///*.A4L
        ///*.A4M
        ///*.A4P
        ///*.A4W
        ///*.A51
        ///*.A5L
        ///*.A5W
        ///*.A60
        ///*.A64
        ///*.A8
        ///*.A80
        ///*.A86
        ///*.AA
        ///*.AAC
        ///*.AAF
        ///*.AAM
        ///*.AAS
        ///*.AB
        ///*.AB$
        ///*.AB3
        ///*.AB6
        ///*.AB65
        ///*.AB8
        ///*.ABC
        ///*.ABD
        ///*.ABF
        ///*.ABG
        ///*.ABI
        ///*.ABK
        ///*.ABM
        ///*.ABO
        ///*.ABR
        ///*.ABS
        ///*.ABT
        ///*.ABW
        ///*.ABX
        ///*.AC
        ///*.AC$
        ///*.AC0
        ///*.AC1
        ///*.AC1D
        ///*.AC2
        ///*.AC3
        ///*.AC3D
        ///*.AC4
        ///*.AC5
        ///*.AC6
        ///*.AC7
        ///*.AC8
        ///*.AC9
        ///*.ACA
        ///*.aCa2
        ///*.ACAD
        ///*.ACB
        ///*.ACC
        ///*.ACD
        ///*.ACE
        ///*.ACF
        ///*.ACG
        ///*.ACGI
        ///*. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string src {
            get {
                return ResourceManager.GetString("src", resourceCulture);
            }
        }
    }
}
